# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Felix Lam
title: Computer Science Student - Focus in Artificial Intelligence
email: quochoan.lam@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: lamqhoan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: lq.hoan
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: lamqhoan
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Felix and I'm a student at the University of Toronto, currently pursuing a BSc. in Computer Science with a focus in Artificia Intelligence. Apart from pursuing my academic goals, I also have experience making web apps. I have interned at a company gaining teamwork and communication skills.

  I am most skilled in: <mark>Python</mark>, <mark>C</mark>, <mark>Java</mark>, <mark>JS/TS</mark>, <mark>React/Angular</mark>, <mark>SQL</mark>, <mark>Data Structure</mark>, <mark>Flask</mark>, <mark>Android Studio</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Uber Eats for UofT Students
        link: github.com/lamqhoan/team15
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/lamqhoan/team15
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is a additional way for student to earn extra money while moving between classes
        description: | # this will include new lines to allow paragraphs
          I started this project as part of a course and a way to learn <mark>React</mark> and we made it to become a fully functional web app. I have learned many skills through this (more specifically coding skills) and been I'm very proud of having this in my portfolio.

      - layout: top-middle
        title: PharmDx Care 
        link: github.com/PharmDx-care-CS301
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/PharmDx-care-CS301
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is a bridge between pharmacies and patients to reduce heavy loads on hospitals
        description: | # this will include new lines to allow paragraphs
          I started this project as part of a course and to acquire skills for software engineerin. I have learned many skills along the way both technical skills, communication skills and teamworking skills


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
          title: SOTI Inc
          sub_title: Software Developer
          caption: May 2020 - August 2021
          quote: >
            SOTI is a proven leader at creating innovative solutions that reduce the cost and complexity of business-critical mobility and the IoT. 
          description: | # this will include new lines to allow paragraphs
              During my time at SOTI as a Software Developer, I was able to do the following
              - Develop innovative solutions to tackle big industry problems.
              - Write well designed, scalable, reliable, testable and reusable code by using best software development practices, clean code and solid principles.
              - Provide technical guidance on the research and development of new products and services.
              - Detect, report, investigate, and fix product defects.
              - Automation, including writing unit and integration tests.
              - Optimize and apply best practices.
              - Maintain high standards of quality for code, technical documentation, and deliverables.
        
        - layout: left
          title: University of Toronto
          sub_title: Teaching Assistant
          caption: January 2021 - April 2021
          quote: >

          description: | # this will include new lines to allow paragraphs
              During my time at UofT as a TA for course titled *Introduction to Computer Science*, I facilitated a discussion tutorial, held weekly office hours, grade assignments and tests. I led a class of roughly 30 students.
      
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Toronto
        caption: 2017 - 2022
        sub_title: BSc Computer Science
        quote: >
          Founded in 1827, the University of Toronto has evolved into Canada’s leading institution of learning, discovery and knowledge creation. We are proud to be one of the world’s top research-intensive universities, driven to invent and innovate.
        description: | # this will include new lines to allow paragraphs
          During my time at UofT I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a general member of *University of Toronto Vietnamese Student Association*.
          CGPA: 3.21.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Hitting the gym
      - Gaming
      - Soccer

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
